### ISSUE TITLE
Create `use_cookie` and `use_indexed_db` Hooks

### ISSUE THREAD

**Issue by Archmonger** [reactive-python/reactpy#857]
### Current Situation

Currently, there is no convenient way of storing/retrieving purely client sided data.

### Proposed Actions

After we migrate `use_query` to core, it makes a lot of sense to add a [`use_cookie`](https://www.npmjs.com/package/@use-hook/use-cookie) hook and [`use_indexed_db`](https://www.npmjs.com/package/use-indexeddb) hook.

This might require expanding the IDOM framework to allow hooks to execute JavaScript. So perhaps these hooks are reliant on a `use_script` hook?

The `use_script` hook may mean we want to create a FIFO "script processor" on the client side, and then have some method of reporting them back to the server (perhaps [this](https://github.com/idom-team/idom/issues/574#issuecomment-1358194045) is related?).

**Comment by rmorshea** [comment]
This seems to describe a need for third party libraries to subscribe to, and send messages over, the websocket both on the server and the client. This simply isn't possible now and would require a rewrite of the messaging protocol (of which there really isn't one) the server and client use now. I mention this briefly in [this comment](https://github.com/idom-team/idom/issues/574#issuecomment-1358194045).

While defining scripts in the form of a hook is probably more convenient and React-like. I think you can probably get away with using the `script` element since it will re-execute if the script source changes.

**Comment by Archmonger** [comment]
the `reactpy.html.script` element is definitely not appropriate for complex tasks such as read/write/modify the client side indexed_db.

**Comment by Archmonger** [comment]
Closing this in favor of #894
